language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
