language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./retest
